## Read in and clean WA file

input_path <- "C:/Users/koenn/OneDrive/WhatsApp Chat with StRiEmEiJeRs GaNg 0345.txt" # Path to exported WA text file
output_path <- "C:/Users/koenn/OneDrive/wa.txt" # Path to the output file that will be generated by this script

library(readr)
library(stringi)
WA <- read_delim(
  input_path, 
  "-", 
  escape_double = FALSE, 
  col_names = FALSE, 
  trim_ws = TRUE,
  na = "empty"
  )

assertthat::assert_that(ncol(WA == 2), 
                        msg="Something went wrong. The parsed file MUST have two columns")
WA <- WA[,2]

# Remove emoji codes
WA <- sapply(WA, function(x) gsub("<U\\+[[:alnum:]]{1,}>", "", x))

# Remove empty lines
namen <- c (
  "Koen Niemeijer: ",
  "Kevin Algera: ",
  "Willem Smits: ",
  "Gijs Cunnen: ",
  "Thijs van der Putten: ",
  "Michiel Arts: ",
  "Thomas Bardoel: ",
  "Yoram Carboex: ",
  "Wescel Manders: "
)
for(naam in namen)
  WA = WA[!stri_endswith_fixed(naam, WA)]

# Remove lines ending with <Media omitted>
WA <- WA[!stri_endswith_fixed("<Media omitted>", WA)]

# Write data to file
write.table(
  x = WA, 
  file = output_path,
  append = FALSE
  quote = FALSE, 
  eol="\n",
  row.names = FALSE,
  col.names = FALSE,
  na = ""
  )